releases:

  - name: vault
    chart: hashicorp/vault
    namespace: vault
    version: 0.20.1
    values:
      - server:
          dev: { enabled: true }
          postStart: ['sh', '-c', 'vault kv get secret/foo || vault kv put secret/foo hello=world']

  - name: external-secrets
    chart: external-secrets/external-secrets
    version: 0.7.2
    namespace: es
    needs: [vault/vault]
    values:
      - installCRDs: true

  - name: config
    chart: ./charts/config
    needs: [es/external-secrets]
    namespace: default
    version: 0.1.0

repositories:
 - name: hashicorp
   url: https://helm.releases.hashicorp.com
 - name: external-secrets
   url: https://charts.external-secrets.io

helmDefaults:
  wait: true
  createNamespace: true
